### ISSUE TITLE
Unable to read font 'helvetica'

### ISSUE THREAD

**Issue by deepakpjose** [dooman87/imagemagick-docker#38] opened 2023-02-12 14:48 UTC
Hi Team,

I'm trying to add text on an image. But I'm getting following error.
'convert: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1619.'

Command used:
docker run  -v imagemagick:/imgs dpokidov/imagemagick $1 label:'Faerie Dragon' -font Z003-Medium-Italic -gravity Center -append $3

I've listed the font's supported and I see Z003-Medium-Italic. So, can some one please help me with correct command?

Thanks,
Deepak

**Comment by dooman87** [comment] 2023-02-26 10:39
Hi,

Thanks for reporting this. Could you please provide what you use for `$1` and `$3`, so I can reproduce?

**Comment by deepakpjose** [comment] 2023-02-26 11:40
Thanks for looking into htis.

$1 is source image and $3 is the generated image after writing label 'Faerie Dragon' into image in $1.

**Comment by dooman87** [comment] 2023-02-27 09:52
Hi there,

I always forget that for IM the argument position matters, so you need to specify the font before `label`. Otherwise, it defaults to "helvetica" which is not installed.

This command should work:

```
docker run -v imagemagick:/imgs dpokidov/imagemagick $1 -font Z003-Medium-Italic label:'Faerie Dragon'  -gravity Center -append $3
```

Let me know if that helps and we can close the issue.

**Comment by dooman87** [comment] 2023-03-14 16:34
Closing due to no further activity

**Closed as completed by dooman87** 2023-03-14 16:34 UTC
